## Determinación de los elementos osculatrices de la Luna

Tomar la posición relativa de la Luna respecto de la Tierra en una fecha dada y voy a determinar $(p,e,i,\Omega,\omega,f)$.

Usamos NASA Horizons para las condiciones iniciales: https://ssd.jpl.nasa.gov/horizons.cgi

In [8]:
# Datos de la Luna
mu_luna=4902.800066 # km^3/s^2
mu_tierra=398600.435436 # km^3/s^2
G=6.67408e-20 # km^3/(kg s^2)

mluna=mu_luna/G
mtierra=mu_tierra/G
mluna,mtierra

(7.346031312180854e+22, 5.972365261369357e+24)

In [13]:
# Vector relativo en kg-km-s (orbitales)
from numpy import array

rvec=array([-3.176502419832263E+05,-2.418831750401069E+05,3.655582402218442E+04]) #km
vvec=array([5.607870632956331E-01,-7.999322621097942E-01,-1.639331278680323E-03]) #km/s

In [14]:
# Unidades 
UL = 3.83e5 # km
UM = mtierra+mluna
from numpy import sqrt
UT = sqrt(UL**3/(G*UM))
UV = UL/UT

UT/86400

4.318778271891243

In [15]:
# Condiciones iniciales a las unidades canónicas
mu=1
rvec=rvec/UL
vvec=vvec/UV

rvec,vvec

(array([-0.829374  , -0.63154876,  0.09544602]),
 array([ 0.54635367, -0.77934381, -0.00159714]))

In [20]:
# Vectores clave
from numpy import cross
from numpy.linalg import norm
r=norm(rvec)
hvec = cross(rvec,vvec)
evec = cross(vvec,hvec)-rvec/r
nvec = cross([0,0,1],hvec)

hvec,evec,nvec

(array([0.07539393, 0.05082266, 0.99141647]),
 array([ 0.01970893,  0.06151967, -0.00465246]),
 array([-0.05082266,  0.07539393,  0.        ]))

In [23]:
h=norm(hvec)
e=norm(evec)

p=h**2/mu
a=p/(1-e**2)

e,p*UL,a*UL

(0.06476694137435804, 379619.56864546525, 381218.6882904266)

In [26]:
# Orientación de la órbita
from numpy import arccos,dot,pi
ip=arccos(dot(hvec,[0,0,1])/h)
i=ip

i*180/pi

5.240010960708313

In [30]:
Wp=arccos(dot(nvec,[1,0,0])/norm(nvec))
W=Wp if nvec[1]>0 else 2*pi-Wp

W*180/pi

123.98370376817692

In [32]:
wp=arccos(dot(nvec,evec)/(norm(nvec)*norm(evec)))
w=wp if evec[2]>=0 else 2*pi-wp

w*180/pi

308.13590250830623